### ISSUE TITLE
Current API is asking for only 3 keys for token

### ISSUE THREAD

**Issue by srebella** [devinrader/video-quickstart-csharp-angular#2]
Hello,

Current Twilio APi is asking for Account SID, API Key and API Secret to create a valid access token, is this code still updated and working?
Thanks

**Comment by devinrader** [comment]
iirc this code uses the now deprecated Conversations API's rather than the current Rooms API's.

**Comment by srebella** [comment]
ok, thanks for the info! Will have to find the way then to make it work for Rooms API.
